<?xml version="1.0"?>

<robot name="hexatilt" xmlns:xacro="http://ros.org/wiki/xacro">
  <!--  Convenience Parameters -->

  <xacro:property name="DP" value="${load_yaml('../param/drone_parameter.yaml')}"/>
  <xacro:property name="namespace" value="/drone" />
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="deg_to_rad" value="0.017453278"/>
  <xacro:property name="to_kgm2" value="1e-9"/>
  <xacro:property name="sin30" value="0.5" />
  <xacro:property name="cos30" value="0.866025403784" />
  <xacro:property name="sqrt2" value="1.4142135623730951" />
  <!-- Mesh parameters -->
  <xacro:property name="mesh_file" value="hexatilt_base_down.dae" />
  <xacro:property name="mesh_scale" value="1 1 1"/>
  <xacro:property name="mesh_scale_prop" value="1 1 1"/>
  <xacro:property name="mesh_scale_leg" value="1 1 1"/>

  <!-- Geometric Parameters -->
  <!-- These parameters are pulled from the .yaml file -->
  <xacro:property name="base_mass" 			value="${DP['urdf/base_mass']}" /> <!-- [kg] -->
  <xacro:property name="rotor_tilt_angle"   value="${DP['urdf/alpha']}"/> <!--in [deg]-->
  <xacro:property name="body_radius"        value="${DP['urdf/base_radius']}" /> <!-- [m] -->
  <xacro:property name="body_height"        value="${DP['urdf/base_height']}" /> 
  <xacro:property name="mass_prop"         	value="${DP['urdf/propeller_mass']}" /> <!-- [kg] -->
  <xacro:property name="arm_length"       	value="${DP['urdf/arm_length']}" /> <!-- [m] -->
  <xacro:property name="radius_leg"         value="${DP['urdf/leg_radius']}" /> <!--[m] -->
  <xacro:property name="length_leg"         value="${DP['urdf/leg_length']}" /> <!-- [m] -->
  <xacro:property name="mass_leg" 			value="${DP['urdf/leg_mass']}"  /> <!-- [kg] -->
  <xacro:property name="rotor_offset_top"   value="${DP['urdf/propeller_offset_top']}"/> <!-- [m] -->
  <xacro:property name="radius_rotor"       value="${DP['urdf/propeller_radius']}" /> <!-- [m] -->

   <!-- Simulation Properties -->
  <xacro:property name="max_leg_velocity" value="0.10" /> <!-- [m] -->
  <xacro:property name="rotor_velocity_slowdown_sim" value="10" />
  <xacro:property name="max_rot_velocity" value="1100" /> <!-- [rad/s] -->
  <xacro:property name="color" value="DarkGrey" />

  <!-- Property Blocks -->
 <!-- Mass and inertial Properties -->
  <xacro:property name="leg_pos_side_y" value="0.11" /> <!-- [m] -->


  <xacro:include filename="$(find flypulator_description)/urdf/gazebo_plugins.xacro" />


<!-- Moment of Inertia at Origin   (g mm^2) -->
  <xacro:property name="body_inertia">
    <inertia
    ixx = "${1.223E+08  *to_kgm2}"
	ixy = "${-7.268E+04 *to_kgm2}"
	ixz = "${-1.303E+04 *to_kgm2}"
	iyx = "${-7.268E+04 *to_kgm2}"
	iyy = "${1.232E+08  *to_kgm2}"
	iyz = "${-2.035E+04 *to_kgm2}"
	izx = "${-1.303E+04 *to_kgm2}"
	izy = "${-2.035E+04 *to_kgm2}"
	izz = "${2.355E+08  *to_kgm2}"     />
    </xacro:property>
 <!-- The inertia of the legs are set to zero and the MoI of the body includes the legs. -->
  <xacro:property name="leg_inertia"> 
    <inertia 
    ixx = "${ 0*to_kgm2 }"
    ixy = "${ 0*to_kgm2 }"
    ixz = "${ 0*to_kgm2 }" 
    iyx = "${ 0*to_kgm2 }"
    iyy = "${ 0*to_kgm2 }"
    iyz = "${ 0*to_kgm2 }"
    izx = "${ 0*to_kgm2 }"
    izy = "${ 0*to_kgm2 }"
    izz = "${ 0*to_kgm2 }"/>
     </xacro:property>
                        
  <xacro:property name="rotor_inertia"> 
    <inertia 
    ixx = "${ 8.686E+04*to_kgm2 }"
    iyy = "${ 3.609E+04*to_kgm2 }"
    izz = "${ 1.079E+05*to_kgm2 }"  
    ixy = "${ 4.600E+04*to_kgm2 }"
	ixz = "${ 1.113E+04*to_kgm2 }"
    izx = "${ 1.113E+04 *to_kgm2 }"
	izy = "${ -1.849E+04*to_kgm2 }"
	iyx = "${ 4.600E+04 *to_kgm2 }"
    iyz = "${ -1.849E+0*to_kgm2 }"/>  
	  </xacro:property>

    <!-- Included URDF Files -->
  <xacro:include filename="$(find flypulator_description)/urdf/multirotor_base.xacro" />

  <!-- Instantiate multirotor_base_macro once -->
  <xacro:multirotor_base_macro
    robot_namespace="${namespace}"
    mass="${base_mass}"
    body_radius="${body_radius}"
    body_height="${body_height}"
    mesh_file="${mesh_file}"
    mesh_scale="${mesh_scale}"
    color="${color}">
    <xacro:insert_block name="body_inertia" />
  </xacro:multirotor_base_macro>

  <!-- Instantiate rotors -->
  <!-- suffix, max_rot_velocity, mesh are currently unused. -->
 
 <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="front_right"
    direction="ccw"
    parent="base_link"
    mass_propeller="${mass_prop}"
    radius_rotor="${radius_rotor}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="1"
    mesh="hexatilt_prop"
    mesh_scale="${mesh_scale_prop}"
    color="Red">
    <origin xyz="${arm_length*cos30} -${arm_length*sin30} ${rotor_offset_top}" rpy="-${rotor_tilt_angle*deg_to_rad} 0  ${150*deg_to_rad}" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>


  <xacro:vertical_rotor robot_namespace="${namespace}"
    suffix="front_left"
    direction="cw"
    parent="base_link"
    mass_propeller="${mass_prop}"
    radius_rotor="${radius_rotor}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="2"
    mesh="hexatilt_prop"
    mesh_scale="${mesh_scale_prop}"
    color="Red">
    <origin xyz="${arm_length*cos30} ${arm_length*sin30} ${rotor_offset_top}" rpy= "${rotor_tilt_angle*deg_to_rad} 0  ${210*deg_to_rad}"/>
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>


  <xacro:vertical_rotor robot_namespace="${namespace}"
    suffix="left"
    direction="ccw"
    parent="base_link"
    mass_propeller="${mass_prop}"
    radius_rotor="${radius_rotor}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="3"
    mesh="hexatilt_prop"
    mesh_scale="${mesh_scale_prop}"
    color="DarkGrey">
    <origin xyz="0 ${arm_length} ${rotor_offset_top}" rpy="-${rotor_tilt_angle*deg_to_rad} 0  -${90*deg_to_rad}" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="back_left"
    direction="cw"
    parent="base_link"
    mass_propeller="${mass_prop}"
    radius_rotor="${radius_rotor}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="4"
    mesh="hexatilt_prop"
    mesh_scale="${mesh_scale_prop}"
    color="DarkGrey">
    <origin xyz="-${arm_length*cos30} ${arm_length*sin30} ${rotor_offset_top}" rpy="${rotor_tilt_angle*deg_to_rad} 0  -${30*deg_to_rad}" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor robot_namespace="${namespace}"
    suffix="back_right"
    direction="ccw"
    parent="base_link"
    mass_propeller="${mass_prop}"
    radius_rotor="${radius_rotor}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="5"
    mesh="hexatilt_prop"
    mesh_scale="${mesh_scale_prop}"
    color="DarkGrey">
    <origin xyz="-${arm_length*cos30} -${arm_length*sin30} ${rotor_offset_top}" rpy= "-${rotor_tilt_angle*deg_to_rad} 0  ${30*deg_to_rad}"/>
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>


  <xacro:vertical_rotor robot_namespace="${namespace}"
    suffix="right"
    direction="cw"
    parent="base_link"
    mass_propeller="${mass_prop}"
    radius_rotor="${radius_rotor}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="6"
    mesh="hexatilt_prop"
    mesh_scale="${mesh_scale_prop}"
    color="DarkGrey">
    <origin xyz="0 -${arm_length} ${rotor_offset_top}" rpy="${rotor_tilt_angle*deg_to_rad} 0  ${90*deg_to_rad}" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>



<xacro:landing_gear robot_namespace="${namespace}"
    suffix="left"
    parent="base_link"
    mass_leg="${mass_leg}"
    radius_leg="${radius_leg}"
    max_leg_velocity="${max_leg_velocity}"
    leg_number="1"
    mesh="hexatilt_leg"
    length_leg="${length_leg}"
    mesh_scale="${mesh_scale_leg}"
    color="DarkGrey"
    reflect="-1">
    <origin xyz="0 ${leg_pos_side_y} -0.02" rpy="0 ${10*deg_to_rad} -${90*deg_to_rad}" />
    <xacro:insert_block name="leg_inertia" />
  </xacro:landing_gear>


<xacro:landing_gear robot_namespace="${namespace}"
    suffix="right"
    parent="base_link"
    mass_leg="${mass_leg}"
    radius_leg="${radius_leg}"
    max_leg_velocity="${max_leg_velocity}"
    leg_number="2"
    mesh="hexatilt_leg"
    length_leg="${length_leg}"
    mesh_scale="${mesh_scale_leg}"
    reflect="1"
    color="DarkGrey">
    <origin xyz="0 -${leg_pos_side_y} -0.02" rpy="0 ${10*deg_to_rad} ${90*deg_to_rad}" />
    <xacro:insert_block name="leg_inertia" />
  </xacro:landing_gear>


</robot>
