<?xml version="1.0"?>

<robot name="hexatilt" xmlns:xacro="http://ros.org/wiki/xacro">
  <!--  Convenience Parameters -->

  <xacro:property name="DP" value="${load_yaml('../param/drone_parameter.yaml')}"/>
  <xacro:property name="namespace" value="/drone" />
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="deg_to_rad" value="0.017453278"/>
  <xacro:property name="to_kgm2" value="1e-9"/>
  <xacro:property name="sin30" value="0.5" />
  <xacro:property name="cos30" value="0.866025403784" />
  <xacro:property name="sqrt2" value="1.4142135623730951" />
  <!-- Mesh parameters -->
  <xacro:property name="mesh_file" value="hexatilt.dae" />
  <!-- <xacro:property name="mesh_scale" value="0.001 0.001 0.001"/> -->
  <xacro:property name="mesh_scale" value="1 1 1"/>
  <xacro:property name="mesh_scale_prop" value="0.098 0.098 0.098"/>
  <xacro:property name="mesh_scale_leg" value="0.1 0.1 0.1"/>

  <!-- Geometric Parameters -->
  <!-- These parameters are pulled from the .yaml file -->
  <xacro:property name="rotor_tilt_angle"   value="${DP['uav/alpha']}"/> <!--in [deg]-->
  <xacro:property name="body_radius"        value="${DP['uav/base_radius']}" /> <!-- [m] -->
  <xacro:property name="body_height"        value="${DP['uav/base_height']}" /> 
  <xacro:property name="mass_rotor"         value="${DP['uav/blade_mass']}" /> <!-- [kg] -->
  <xacro:property name="arm_length_x"       value="${DP['uav/x']}" /> <!-- [Man[m] -->
  <xacro:property name="arm_length_y"       value="${DP['uav/y']}" /> <!-- [m] -->
  <xacro:property name="arm_length_side_x"  value="${DP['uav/side_x']}" /> <!-- [m] -->
  <xacro:property name="arm_length_side_y"  value="${DP['uav/side_y']}" /> <!-- [m] -->
  <xacro:property name="radius_leg"         value="${DP['uav/leg_radius']}" /> <!--[Man [m] -->
  <xacro:property name="length_leg"         value="${DP['uav/leg_length']}" /> <!-- [m] -->
  <xacro:property name="rotor_offset_top"   value="${DP['uav/blade_offset_top']}"/> <!-- [m] -->
  <xacro:property name="radius_rotor"       value="${DP['uav/blade_radius']}" /> <!-- [[Manm] -->

   <!-- Simulation Properties -->
  <xacro:property name="max_leg_velocity" value="0.10" /> <!-- [m] -->
  <xacro:property name="rotor_velocity_slowdown_sim" value="10" />
  <xacro:property name="motor_constant" value="8.54858e-06" /> <!-- [kg.m/s^2] -->
  <xacro:property name="moment_constant" value="0.06" /> <!-- [m] -->
  <xacro:property name="time_constant_up" value="0.0125" /> <!-- [s] -->
  <xacro:property name="time_constant_down" value="0.025" /> <!-- [s] -->
  <xacro:property name="max_rot_velocity" value="1100" /> <!-- [rad/s] -->
  <xacro:property name="rotor_drag_coefficient" value="8.06428e-04" />
  <xacro:property name="rolling_moment_coefficient" value="0.000001" />
  <xacro:property name="color" value="DarkGrey" />

  <!-- Property Blocks -->
 <!-- Mass and inertial Properties -->
  <xacro:property name="base_mass" value="${DP['uav/base_mass']}" /> <!-- [kg] -->
  <xacro:property name="leg_pos_side_x" value="0.11" /> <!-- [m] -->
  <xacro:property name="mass_leg" value="0.180" /> <!-- [kg] -->


<!-- Moment of Inertia at Origin   (g mm^2) -->
  <xacro:property name="body_inertia">
    <inertia
    ixx = "${1.536E+08*to_kgm2}"
	ixy = "${ 4.372E+04 *to_kgm2}"
	ixz = "${ 1.475E+04 *to_kgm2}"
	iyx = "${ 4.372E+04 *to_kgm2}"
	iyy = "${ 1.580E+08 *to_kgm2}"
	iyz = "${ -2.790E+04*to_kgm2}"
	izx = "${ 1.475E+04 *to_kgm2}"
	izy = "${ -2.790E+04*to_kgm2}"
	izz = "${ 2.429E+08 *to_kgm2}"     />
    </xacro:property>

  <xacro:property name="leg_inertia"> 
    <inertia 
    ixx = "${ 3.321E+06*to_kgm2 }"
    ixy = "${ 0.048    *to_kgm2 }"
    ixz = "${ 4.097E+05*to_kgm2 }" 
    iyx = "${ 0.048    *to_kgm2 }"
    iyy = "${ 2.407E+06*to_kgm2 }"
    iyz = "${ -0.271    *to_kgm2 }"
    izx = "${ 4.097E+05*to_kgm2 }"
    izy = "${ -0.271   *to_kgm2 }"
    izz = "${ 1.070E+06*to_kgm2 }"/>
     </xacro:property>
                        
  <xacro:property name="rotor_inertia"> 
    <inertia 
    ixx = "${ 8.686E+04*to_kgm2 }"
    iyy = "${ 3.609E+04*to_kgm2 }"
    izz = "${ 1.079E+05*to_kgm2 }"  
    ixy = "${ 4.600E+04*to_kgm2 }"
	ixz = "${ 1.113E+04*to_kgm2 }"
    izx = "${ 1.113E+04 *to_kgm2 }"
	izy = "${ -1.849E+04*to_kgm2 }"
	iyx = "${ 4.600E+04 *to_kgm2 }"
    iyz = "${ -1.849E+0*to_kgm2 }"/>  
	  </xacro:property>

    <!-- Included URDF Files -->
  <xacro:include filename="$(find flypulator_description)/urdf/multirotor_base.xacro" />

  <!-- Instantiate multirotor_base_macro once -->
  <xacro:multirotor_base_macro
    robot_namespace="${namespace}"
    mass="${base_mass}"
    body_radius="${body_radius}"
    body_height="${body_height}"
    mesh_file="${mesh_file}"
    mesh_scale="${mesh_scale}"
    color="${color}">
    <xacro:insert_block name="body_inertia" />
  </xacro:multirotor_base_macro>

  <!-- Instantiate rotors -->
 
  <xacro:vertical_rotor robot_namespace="${namespace}"
    suffix="back_right"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="1"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    mesh="hexatilt_prop"
    mesh_scale="${mesh_scale_prop}"
    color="DarkGrey">
    <origin xyz="-${arm_length_x+0.01} -${arm_length_y} ${rotor_offset_top}" rpy= "-${rotor_tilt_angle*deg_to_rad} 0  ${60*deg_to_rad}"/>
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

 <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="front_right"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="2"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    mesh="hexatilt_prop"
    mesh_scale="${mesh_scale_prop}"
    color="DarkGrey">
    <origin xyz="${arm_length_x+0.01} -${arm_length_y} ${rotor_offset_top}" rpy="${rotor_tilt_angle*deg_to_rad} 0  ${120*deg_to_rad}" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor robot_namespace="${namespace}"
    suffix="back_right"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="3"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    mesh="hexatilt_prop"
    mesh_scale="${mesh_scale_prop}"
    color="DarkGrey">
    <origin xyz="${arm_length_side_x} -${arm_length_side_y} ${rotor_offset_top}" rpy="-${rotor_tilt_angle*deg_to_rad} 0  ${180*deg_to_rad}" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor robot_namespace="${namespace}"
    suffix="front_left"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="4"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    mesh="hexatilt_prop"
    mesh_scale="${mesh_scale_prop}"
    color="Red">
    <origin xyz="${arm_length_x-0.02} ${arm_length_y} ${rotor_offset_top}" rpy= "${rotor_tilt_angle*deg_to_rad} 0  ${240*deg_to_rad}"/>
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>


  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="back_left"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="5"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    mesh="hexatilt_prop"
    mesh_scale="${mesh_scale_prop}"
    color="Red">
    <origin xyz="-${arm_length_x-0.02} ${arm_length_y} ${rotor_offset_top}" rpy="-${rotor_tilt_angle*deg_to_rad} 0  -${60*deg_to_rad}" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor robot_namespace="${namespace}"
    suffix="back_right"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="6"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    mesh="hexatilt_prop"
    mesh_scale="${mesh_scale_prop}"
    color="DarkGrey">
    <origin xyz="-${arm_length_side_x} -${arm_length_side_y} ${rotor_offset_top}" rpy="${rotor_tilt_angle*deg_to_rad} 0  ${0*deg_to_rad}" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>



<xacro:landing_gear robot_namespace="${namespace}"
    suffix="left"
    parent="base_link"
    mass_leg="${mass_leg}"
    radius_leg="${radius_leg}"
    max_leg_velocity="${max_leg_velocity}"
    leg_number="1"
    mesh="hexatilt_leg"
    length_leg="${length_leg}"
    mesh_scale="${mesh_scale_leg}"
    color="DarkGrey"
    reflect="-1">
    <origin xyz="${leg_pos_side_x} 0 -0.02" rpy="0 -${10*deg_to_rad} 0" />
    <xacro:insert_block name="leg_inertia" />
  </xacro:landing_gear>


<xacro:landing_gear robot_namespace="${namespace}"
    suffix="right"
    parent="base_link"
    mass_leg="${mass_leg}"
    radius_leg="${radius_leg}"
    max_leg_velocity="${max_leg_velocity}"
    leg_number="2"
    mesh="hexatilt_leg"
    length_leg="${length_leg}"
    mesh_scale="${mesh_scale_leg}"
    reflect="1"
    color="DarkGrey">
    <origin xyz="-${leg_pos_side_x} 0 -0.02" rpy="0 ${10*deg_to_rad} 0" />
    <xacro:insert_block name="leg_inertia" />
  </xacro:landing_gear>


<!-- Gazebo plugins .. move to import document.. -->
  <gazebo>
    <plugin name="fake_sensor_plugin" filename="libfake_sensor_plugin.so">
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>${namespace}</robotNamespace>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="propulsion_plugin" filename="libpropulsion_plugin.so">
    </plugin>
  </gazebo>

</robot>
