<?xml version="1.0"?>
<!--  multirotor_base.xacro -->
 <!-- This file contains the macros for the UAV. 
    The following macros are defined here: 
    * mulitirotor_base_macro 
    * vertical_rotor 
    * landing_gear --> 

    <!-- The gazebo plugins that were used in px4 are located at /src/Firmware/Tools/sitl_gazebo/src. (have to clone their firmware folder) Can be viewed for comparison with our own plugins -->

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Main multirotor link -->
  <xacro:macro name="multirotor_base_macro"
    params="robot_namespace mass body_radius body_height mesh_file mesh_scale color *inertia">
    <link name="base_link"></link>

    <joint name="base_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="base_link_inertia" />
    </joint>

    <link name="base_link_inertia">
      <inertial>
        <mass value="${mass}" />  <!-- [kg] -->
        <origin xyz="0 0 0" />
        <xacro:insert_block name="inertia" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://flypulator_description/meshes/${mesh_file}"
            scale="${mesh_scale}" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <cylinder length="${body_height}" radius="${body_radius}" /> <!-- [m] -->
        </geometry>
      </collision>
    </link>

    <!--PX4 memory: attach multirotor_base_plugin to the base_link -->
    <gazebo>
    </gazebo>
    <gazebo reference="base_link">
    <material>Gazebo/${color}</material>
    </gazebo>
  </xacro:macro>

  <!-- Rotor joint and link -->
  <xacro:macro name="vertical_rotor"
    params="robot_namespace suffix direction motor_constant moment_constant parent mass_rotor radius_rotor time_constant_up time_constant_down max_rot_velocity motor_number rotor_drag_coefficient rolling_moment_coefficient color mesh mesh_scale *origin *inertia">

    <joint name="blade_joint_${motor_number}" type="continuous">
      <xacro:insert_block name="origin" />
      <axis xyz="0 0 1" />
      <parent link="${parent}" />
      <child link="blade_link_${motor_number}" />

    </joint>
    <link name="blade_link_${motor_number}">
      <inertial>
        <mass value="${mass_rotor}" /> <!-- [kg] -->
        <xacro:insert_block name="inertia" />
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://flypulator_description/meshes/${mesh}_${direction}.dae"
            scale="${mesh_scale}" />
          <!-- <box size="${2*radius_rotor} 0.01 0.005"/> -->
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.005" radius="${radius_rotor}" /> <!-- [m] -->
        </geometry>
      </collision>
    </link>
    <!--PX4 memory: attach librotors_gazebo_motor_model to the base_link -->
    <gazebo>
         </gazebo>
    <gazebo reference="blade_link_${motor_number}">
      <material>Gazebo/${color}</material>
    </gazebo>
  </xacro:macro>

  <!-- Landing gear links and joints -->
  <xacro:macro name="landing_gear"
    params="robot_namespace suffix reflect parent mass_leg radius_leg length_leg max_leg_velocity leg_number color mesh mesh_scale *origin *inertia">

<!-- Landing gear joint: -->
    <joint name="leg_${leg_number}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <axis xyz="0 1 0" />
          <parent link="${parent}" />
      <child link="leg_${leg_number}" />
    </joint>

<!-- Leg link -->
    <link name="leg_${leg_number}">
      <inertial>
        <origin xyz="0 0 -${length_leg/2}" rpy="0 0 0 " />
        <mass value="${mass_leg}" /> <!-- [kg] -->
        <xacro:insert_block name="inertia" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0 " />
        <geometry>
          <mesh filename="package://flypulator_description/meshes/right_leg.dae"
             scale="${mesh_scale}" /> 
            <!-- <cylinder length="${length_leg}" radius="${radius_leg}" /> <1 [m] -1> -->
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 -${length_leg/2}" rpy="0 0 0 " />
        <geometry>
            <cylinder length="${length_leg}" radius="${radius_leg}" /> <!-- [m] -->
        </geometry>
      </collision>
    </link>

<!-- Joint Leg-foot fixed -->
    <joint name="foot_${leg_number}_joint" type="fixed">
      <parent link="leg_${leg_number}" />
      <child link="foot_${leg_number}" />
      <origin xyz="0 0 -${length_leg}" rpy= "1.57 0 0"/> 

    </joint>
<!-- Foot link -->
    <link name="foot_${leg_number}">
      <inertial>
        <mass value="${mass_leg}" /> <!-- [kg] -->
        <xacro:insert_block name="inertia" />
      </inertial>
      <!-- <visual> -->
        <!-- <geometry> -->
<!-- This is not populated as dae shows leg and foot. -->
        <!-- </geometry> -->
      <!-- </visual> -->
      <collision>
        <geometry>
            <cylinder length="${length_leg}" radius="${radius_leg}" /> <!-- [m] -->
        </geometry>
      </collision>
    </link>

    <gazebo>
         </gazebo>
    <gazebo reference="leg_${leg_number}">
      <material>Gazebo/${color}</material>
    </gazebo>
  </xacro:macro>
</robot>









